// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3gVN2N-DwQfYcsKIVMhrKqn0PIvYOvkA',
    appId: '1:683392500098:web:a03f6f4a6e769189414f9b',
    messagingSenderId: '683392500098',
    projectId: 'taskmanager01-c5b07',
    authDomain: 'taskmanager01-c5b07.firebaseapp.com',
    storageBucket: 'taskmanager01-c5b07.firebasestorage.app',
    measurementId: 'G-GRJCQWXTY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqKnGTE6Ma-D-8xWBEVjlD-Jr-hvtB9L0',
    appId: '1:683392500098:android:3c3b8b4afff545d8414f9b',
    messagingSenderId: '683392500098',
    projectId: 'taskmanager01-c5b07',
    storageBucket: 'taskmanager01-c5b07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuS0a1ivDHwnKDY8embNprPJr2umGH68',
    appId: '1:683392500098:ios:fcffa415ed41e9c1414f9b',
    messagingSenderId: '683392500098',
    projectId: 'taskmanager01-c5b07',
    storageBucket: 'taskmanager01-c5b07.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuS0a1ivDHwnKDY8embNprPJr2umGH68',
    appId: '1:683392500098:ios:fcffa415ed41e9c1414f9b',
    messagingSenderId: '683392500098',
    projectId: 'taskmanager01-c5b07',
    storageBucket: 'taskmanager01-c5b07.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3gVN2N-DwQfYcsKIVMhrKqn0PIvYOvkA',
    appId: '1:683392500098:web:8e03d416f5b12e69414f9b',
    messagingSenderId: '683392500098',
    projectId: 'taskmanager01-c5b07',
    authDomain: 'taskmanager01-c5b07.firebaseapp.com',
    storageBucket: 'taskmanager01-c5b07.firebasestorage.app',
    measurementId: 'G-3XT6NL2C4Q',
  );
}
